{% set version = '1.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-phylogeneticem
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/PhylogeneticEM_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/PhylogeneticEM/PhylogeneticEM_{{ version }}.tar.gz
  sha256: ba26a39f298c9ef50d6eae95f4f93cc512a964778f25c6ddf41b7f87c96bd80f

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base >=3.6
    - r-linselect >=1.1.1
    - r-mass >=7.3.45
    - r-matrix >=1.2.3
    - r-rcpp >=1.0.2
    - r-rcpparmadillo
    - r-ape >=5.3
    - r-capushe >=1.1.1
    - r-foreach >=1.4.3
    - r-gglasso >=1.4
    - r-glmnet >=2.0.5
    - r-plyr >=1.8.4
    - r-robustbase >=0.92.6
  run:
    - r-base >=3.6
    - {{native}}gcc-libs         # [win]
    - r-linselect >=1.1.1
    - r-mass >=7.3.45
    - r-matrix >=1.2.3
    - r-rcpp >=1.0.2
    - r-rcpparmadillo
    - r-ape >=5.3
    - r-capushe >=1.1.1
    - r-foreach >=1.4.3
    - r-gglasso >=1.4
    - r-glmnet >=2.0.5
    - r-plyr >=1.8.4
    - r-robustbase >=0.92.6

test:
  commands:
    - $R -e "library('PhylogeneticEM')"           # [not win]
    - "\"%R%\" -e \"library('PhylogeneticEM')\""  # [win]

about:
  home: https://github.com/pbastide/PhylogeneticEM
  license: GPL (>= 2)
  summary: " Implementation of the automatic shift detection method for Brownian Motion (BM)
    or Ornstein\xE2\u20AC\u201CUhlenbeck (OU) models of trait evolution on phylogenies.
    Some tools to handle equivalent shifts configurations are also available. See Bastide
    et al. (2017) <doi:10.1111/rssb.12206> and Bastide et al. (2018) <doi:10.1093/sysbio/syy005>."
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: PhylogeneticEM
# Title: Automatic Shift Detection using a Phylogenetic EM
# Version: 1.3.0
# Authors@R: c( person("Paul", "Bastide", email = "paul.bastide@m4x.org", role = c("aut", "cre")), person("Mahendra", "Mariadassou", role = "ctb"))
# Description:  Implementation of the automatic shift detection method for Brownian Motion (BM) or OrnsteinaUhlenbeck (OU) models of trait evolution on phylogenies. Some tools to handle equivalent shifts configurations are also available. See Bastide et al. (2017) <doi:10.1111/rssb.12206> and Bastide et al. (2018) <doi:10.1093/sysbio/syy005>.
# Depends: ape (>= 5.3), Matrix (>= 1.2.3), R (>= 3.6.0),
# Imports: capushe (>= 1.1.1), foreach (>= 1.4.3), gglasso (>= 1.4), glmnet (>= 2.0.5), graphics (>= 3.6.0), grDevices (>= 3.6.0), LINselect (>= 1.1.1), MASS (>= 7.3.45), methods (>= 3.6.0), plyr (>= 1.8.4), Rcpp (>= 1.0.2), robustbase (>= 0.92.6), stats (>= 3.6.0), utils (>= 3.6.0)
# Suggests: combinat (>= 0.0.8), doParallel (>= 1.0.10), phytools (>= 0.5.38), testthat (>= 1.0.2), TreeSim (>= 2.2), knitr, rmarkdown
# LinkingTo: Rcpp, RcppArmadillo
# License: GPL (>= 2) | file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# URL: https://github.com/pbastide/PhylogeneticEM
# BugReports: https://github.com/pbastide/PhylogeneticEM/issues
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2019-10-02 21:53:37 UTC; bastide
# Author: Paul Bastide [aut, cre], Mahendra Mariadassou [ctb]
# Maintainer: Paul Bastide <paul.bastide@m4x.org>
# Repository: CRAN
# Date/Publication: 2019-10-03 04:20:05 UTC
