appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: wmrc9G20xmH5YbO41vkNwqm5crWLhbWSS6OGNwR62EOQEKWWyYZQMe6sALjecngoyriwPHP64BoBtierhfagE65wipfxqRD0gPsed8PumRdxyX5Fp9ouvj4uNxnPK7E3+uNuk4wsri/6zKFKbJywewI/VQ7ni1Ab0QvbO1zf2Tkxp5M9uxkj/dUm6pn6Scfeu2gdLZVlEcPCL0oLOP20MigiBZfdk8uw9ZZH2j58znWQDmzYsSrbbhyFaswUDS2J6J8u+8vXnNp9P5FjCtl11ATuH6nrZsWXnBYsECuJ2OUo42x9SV65i3Uf7fWatvD9grN5D/tswln9ZXHCfZgbrSvZVJMRp9vLMdW033ACKpsOHwHlygs0W0P9yrd4hieGzbVqaJrJjoQgaWTyAQ3I28m/3SxJcCYhZE5bLb/hEoAeJt/GGMNOgodyDSNOWdh8qanYuLj//MkVVWWtW1zKF5z7ccHX+JduLnEZlH16mKbavb8mLCfbkqqjEkOeFW9jG/iAibxCj3i91LEIkthtfXLHhtfOGTJQf1LI6MiiAVea64QUIFO3xGoX/pola4hMDza31KyoTy0QQ1bYIhBzEh5Dd12USDcSqxyRvGbnZh70M5ZOI60AqsNWgsbx5uDqHjN3IFgn64p/JNvbsBLRM9G3XsMyQtPfThkOeP8N2rg=}
