travis:
  secure:
    BINSTAR_TOKEN: bQ4+sHWFcsSyB1LIxcmrxHVsFkWtIRlV0z8guwMO0XQc5gjoAiuLsveNqHfdwR1oGzPcxpBehg6fUe3CC1kqIr8p4FJf9dBiPH2WdE43FBSrIloE/SO4iK7qC87Sz7EdObDaHDeY6haf2dfA3NYCfHlWnIO+8zK7VqkL/o41T9gkBLO8QSt0HiBwRklyuApQyOKJdXurfsQpukfZEL6JJ462vyq4Avy6v7kFQbbjnC9HrC8OrLE15kfeeIeTZjPF+POzEOmYt9J9PkUoZtN1GRAms1DXYiF/0Ghmz1ahF/cLXWe4ib1CAbx7u8fKBw5VRyvbWckXoWZoab8n65B2RAB5axgPmucC8H0cTa8S6WXzL2eTskbUI9/suS75zEBO5bIZvTet/y/SiufPINNncgdTRgqbeoEHTD+R9k/H7i5l2uOsFHNQBUVxMLneEA1FyC9HtGmomfwVx5e1KHM2Fx9vOiLJ9Mx7AnnLb9NC5AX1HkKmeMVYSkjLRxGkAjSzmOCbWblrvQwaumpbSWtbCPOXFm9fz7h4Ak7tPvYmsXkpyNJ6Far6EgAuJRavipk3m401w9x/7K4s7zr7y0s5WuG4Hf2q18FsAUDFVgOrT6Xh4fRb731rTTcJ+vwWXT0zjq916RExiuyNo5+RLJiBsBXAElPkyE0OV3uo5Hux+Lk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
